using System;
using System.Linq;
using System.Reflection;

namespace HollywoodGraphics;

/// <summary>
/// Resolving a patch target whose name is a number.
///
/// Most of what this mod patches has a real name, and a real name that goes away is a
/// compile error -- the best kind, because it happens on the build machine. A handful do
/// not: `method_5`, `method_1`, `method_41` are names the obfuscator generated by
/// counting, and BSG renumbers them whenever a method is added or removed from the class.
///
/// That fails in three different ways and only one of them is loud:
///
///   1. The number is gone entirely. `GetMethod` returns null, ModulePatch throws, and
///      with the patches enabled one after another in Plugin.Awake that takes the whole
///      mod down. Loud, but it does not say which patch or why.
///   2. The number now names a method with different parameters. Harmony refuses to bind
///      the prefix and throws. Loud enough, once you know to read it that way.
///   3. **The number now names a different method with the same shape.** Nothing throws.
///      The patch applies to the wrong code and the mod is quietly, subtly wrong.
///
/// The third is the one worth spending code on, and it cannot be prevented from here:
/// knowing which method is the right one needs the assembly in front of you. What it can
/// do is stop being invisible. Every numbered target is written to the log with the
/// signature it actually resolved to, so "did this land on the right method after the
/// game updated" is a question the log answers instead of a bisect.
/// </summary>
internal static class PatchTarget
{
    /// <summary>
    /// The method, plus a log line describing exactly what was found.
    /// </summary>
    /// <param name="expected">
    /// What the patch believes it is patching, in the version it was written against, for
    /// the log to be compared with. Free text; nothing is asserted against it, because a
    /// signature this code cannot see is not one it can check.
    /// </param>
    internal static MethodBase Numbered(Type type, string name, string expected)
    {
        var method = type.GetMethod(
            name,
            BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static);

        if (method == null)
        {
            // Said before ModulePatch throws its own, less specific version.
            Plugin.Log.LogError(
                $"[HollywoodPatch] {type.Name}.{name} is gone in this build of the game. "
                + $"It was {expected}. The obfuscator renumbers these when BSG adds or removes "
                + "a method, so the same method is probably still there under another number.");

            return null;
        }

        Plugin.Log.LogInfo($"[HollywoodPatch] {type.Name}.{name} -> {Describe(method)}   (expected {expected})");

        return method;
    }

    private static string Describe(MethodBase method)
    {
        var parameters = string.Join(
            ", ",
            method.GetParameters().Select(p => $"{Short(p.ParameterType)} {p.Name}"));

        var returns = method is MethodInfo info ? Short(info.ReturnType) : "void";

        return $"{returns} {method.Name}({parameters})";
    }

    private static string Short(Type type) => type?.Name ?? "?";
}
